### ISSUE TITLE
question about CUDA Version

### ISSUE THREAD

**Issue by PigBroA** [maggiez0138/Swin-Transformer-TensorRT#1]
Dear maggiez0138,

I have question about CUDA version.

You said you have used TensorRT 8.2.1, and this version depends on CUDA 11.5 as I know.(and there is no torch version for CUDA 11.5 yet, so I have installed torch 1.10 for CUDA 11.3)

I tried to run this code with CUDA 11.5, but I can't success to run any python file, because of container_abcs package.(I searched about this issue, it can be conflict with torch latest version).

Could you please let me know how to run python files(before processing Accuray Test Results on ImageNet-1K Validation Dataset at README) with CUDA 11.5.

Thank you very much.

**Comment by maggiez0138** [comment]
Sorry for late reply.

Actually I have used two environments to do this work.
1) Conda environment, please refer to [Install](https://github.com/microsoft/Swin-Transformer/blob/main/get_started.md#install) session for detail. With this environment, we can run `main.py` to evaluate the accuracy of the PyTorch model, and the `export.py` script can be executed to get the onnx model.

2) TensorRT docker(from NGC, nvcr.io/nvidia/tensorrt:21.12-py3) is mainly used to build TRT engine, run trtexec benchmark, and evaluate the accuracy of TRT engine. The following utils are installed in this docker (it seems torch1.7.1 can be installed on cuda11.5):

pip install torch==1.7.1 torchvision==0.8.2
pip install opencv-python==4.4.0.46 termcolor==1.1.0 yacs==0.1.8
pip install timm==0.3.2
pip install tqdm prettytable scipy
pip install absl-py -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com

**Comment by maggiez0138** [comment]
Close the issue.
