### ISSUE TITLE
Hello, I have not reproduced the income of the batch you mentioned！

### ISSUE THREAD

**Issue by tensorflowt** [maggiez0138/Swin-Transformer-TensorRT#10]
Hello, I have not reproduced the income of the batch you mentioned.
My test machine environment is as follows：
![db1ea281927748d6fb724ac78d7a594](https://user-images.githubusercontent.com/37217594/184485104-6ce539c9-df2b-4ee9-b8eb-26f51fac22dc.png)
The model I tested is as follows:
![58ccc5b3f07202001acbfe88b6930ef](https://user-images.githubusercontent.com/37217594/184486052-c69419e6-ef66-4e9f-9ae3-462dba217ab1.png)
My evaluation script is as follows：
`trtexec --loadEngine=./weights/swin_tiny_patch4_window7_224_batch16.engine`
My test results are as follows:
![2e8c5b16812c75a2076ed3fedc8564f](https://user-images.githubusercontent.com/37217594/184488260-6af0edbd-6d28-4b6a-a56d-86d28e8cc3dd.png)
The specific test screenshots are as follows:
![5434dfd2187e8f4bf3f17004147208a](https://user-images.githubusercontent.com/37217594/184488558-04f5bbeb-13a0-40ef-bff9-88b6a8a66746.png)
![4514d5e49a9f3332dd3462184324ea9](https://user-images.githubusercontent.com/37217594/184488716-97547d68-9722-459c-b2e8-d6dcdc1b5a8a.png)
![0f1954fe7c53e3349a2037b923141ce](https://user-images.githubusercontent.com/37217594/184488782-fc12db25-074c-41ab-b457-f1b95e2e4965.png)

Because, I'm more curious, why are my results so different from yours? same graphics hardware.

Looking forward to your reply and good luck.

**Comment by maggiez0138** [comment]
> Hello, I have not reproduced the income of the batch you mentioned. My test machine environment is as follows： ![db1ea281927748d6fb724ac78d7a594](https://user-images.githubusercontent.com/37217594/184485104-6ce539c9-df2b-4ee9-b8eb-26f51fac22dc.png) The model I tested is as follows: ![58ccc5b3f07202001acbfe88b6930ef](https://user-images.githubusercontent.com/37217594/184486052-c69419e6-ef66-4e9f-9ae3-462dba217ab1.png) My evaluation script is as follows： `trtexec --loadEngine=./weights/swin_tiny_patch4_window7_224_batch16.engine` My test results are as follows: ![2e8c5b16812c75a2076ed3fedc8564f](https://user-images.githubusercontent.com/37217594/184488260-6af0edbd-6d28-4b6a-a56d-86d28e8cc3dd.png) The specific test screenshots are as follows: ![5434dfd2187e8f4bf3f17004147208a](https://user-images.githubusercontent.com/37217594/184488558-04f5bbeb-13a0-40ef-bff9-88b6a8a66746.png) ![4514d5e49a9f3332dd3462184324ea9](https://user-images.githubusercontent.com/37217594/184488716-97547d68-9722-459c-b2e8-d6dcdc1b5a8a.png) ![0f1954fe7c53e3349a2037b923141ce](https://user-images.githubusercontent.com/37217594/184488782-fc12db25-074c-41ab-b457-f1b95e2e4965.png)
> 
> Because, I'm more curious, why are my results so different from yours? same graphics hardware.
> 
> Looking forward to your reply and good luck.

Actually, the throughput should be batchsize*(throughput of trtexec output). So the performance is as expected.
But my perforce is a little better than you, maybe it is because the GPU workload(GPU is busy with other tasks), or GPU frequency, it is really complexed. Overrall, with bigger batchsize(from 1 to 32), the throughput should increase.
