### ISSUE TITLE
avergae FPS of each model

### ISSUE THREAD

**Issue by Linaom1214** [maggiez0138/Swin-Transformer-TensorRT#3]
can provide more detail about inference speed of each model 

the speed compare between each method

thanks

**Comment by maggiez0138** [comment]
> can provide more detail about inference speed of each model
> 
> the speed compare between each method
> 
> thanks

Do you mean the comparison of difference models (Swin-T, Swin-S, Swin-B and Swin-T)?  Will do, if I have the bandwidth.

**Comment by Linaom1214** [comment]
Thanks for the reply, I am more concerned about the difference in inference speed between Transfromer and CNN after TRT acceleration, thanks! ! !
