### ISSUE TITLE
Where are the diagrams below obtained ？

### ISSUE THREAD

**Issue by tensorflowt** [maggiez0138/Swin-Transformer-TensorRT#4]
Hello! Thank you very much for your open source cod！
I would like to know how the results of the analysis below are obtained. How was the QDREP file obtained here?
![FP16](https://user-images.githubusercontent.com/37217594/158159311-a8cbc4f4-cd6e-4d3f-a456-0c1e281b4f6d.png)

Tanks ！

**Comment by maggiez0138** [comment]
> Hello! Thank you very much for your open source cod！ I would like to know how the results of the analysis below are obtained. How was the QDREP file obtained here? ![FP16](https://user-images.githubusercontent.com/37217594/158159311-a8cbc4f4-cd6e-4d3f-a456-0c1e281b4f6d.png)
> 
> Tanks ！

With nsys profile, the command may be as below.

nsys profile -o swin_tiny_patch4_window7_224_no_quant_matmul_batch16 trtexec --loadEngine=./swin_tiny_patch4_window7_224_no_quant_matmul_batch16.engine --warmUp=0 --duration=0 --iterations=50
