### ISSUE TITLE
the link(torch/onnx/symbolic_opset9.py) is expired

### ISSUE THREAD

**Issue by linuxmi** [maggiez0138/Swin-Transformer-TensorRT#6]
Exporting the operator roll to ONNX opset version 9 is not supported.
A: Please refer to [torch/onnx/symbolic_opset9.py](https://github.com/maggiez0138/Swin-Transformer-TensorRT/blob/master/torch/onnx/symbolic_opset9.py), add the support of exporting torch.roll.

the link(https://github.com/maggiez0138/Swin-Transformer-TensorRT/blob/master/torch/onnx/symbolic_opset9.py) is expired

**Comment by Linaom1214** [comment]
> 
torch version update to 1.10

**Comment by maggiez0138** [comment]
Updated Readme.
